/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crudeEstoque;

/**
 *
 * @author kai
 */
public class Inter1 extends javax.swing.JFrame {

    /**
     * Creates new form Inter1
     */
    public Inter1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldQtd_Estoque = new javax.swing.JTextField();
        jTextFieldUn_Medida = new javax.swing.JTextField();
        jTextFieldV_Venda = new javax.swing.JTextField();
        jTextFieldV_Compra = new javax.swing.JTextField();
        jTextFieldQtd_min_estoque = new javax.swing.JTextField();
        jTextFieldCodigo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Nome");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 14, 27, 14);

        jLabel2.setText("Codigo");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 40, 33, 14);

        jLabel3.setText("Quantidade no estoque");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 66, 113, 14);

        jLabel4.setText("Unidade de medida");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 92, 91, 14);

        jLabel5.setText("Valor Venda");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 118, 57, 14);

        jLabel6.setText("Valor Compra");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 144, 64, 14);

        jLabel7.setText("Quantidade Minima No Estoque");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 170, 149, 14);
        getContentPane().add(jTextFieldNome);
        jTextFieldNome.setBounds(55, 11, 228, 20);
        getContentPane().add(jTextFieldQtd_Estoque);
        jTextFieldQtd_Estoque.setBounds(133, 63, 54, 20);
        getContentPane().add(jTextFieldUn_Medida);
        jTextFieldUn_Medida.setBounds(105, 89, 6, 20);
        getContentPane().add(jTextFieldV_Venda);
        jTextFieldV_Venda.setBounds(105, 115, 6, 20);
        getContentPane().add(jTextFieldV_Compra);
        jTextFieldV_Compra.setBounds(105, 141, 6, 20);
        getContentPane().add(jTextFieldQtd_min_estoque);
        jTextFieldQtd_min_estoque.setBounds(163, 167, 6, 20);
        getContentPane().add(jTextFieldCodigo);
        jTextFieldCodigo.setBounds(53, 37, 52, 20);

        jButton1.setText("Açao");
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 270, 57, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inter1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inter1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inter1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inter1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inter1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldQtd_Estoque;
    private javax.swing.JTextField jTextFieldQtd_min_estoque;
    private javax.swing.JTextField jTextFieldUn_Medida;
    private javax.swing.JTextField jTextFieldV_Compra;
    private javax.swing.JTextField jTextFieldV_Venda;
    // End of variables declaration//GEN-END:variables
}
